name: Deploy dev

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Build website
        run: |
          npm install
          npm run build

      - name: Deploy to Azure
        uses: Adam-Shea/deploy-to-azure-storage@1.4.1
        with:
          source-path: dist
          sas-url: ${{ secrets.DEPLOY_SAS_URL }}
