name: Deploy dev

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Build website
        run: |
          npm install
          npm run build

      - name: Deploy to Azure
        run:
          using: 'node12'
          main: 'azure.js'
        inputs:
          source-path:
            description: 'The location of your built site files. (For example, "out".)'
            required: true
            default: dist
          sas-url:
            description: 'A SAS URL for your storage account. (You should store this in a Secret.)'
            required: true
            default: ${{ secrets.DEPLOY_SAS_URL }}
